version: '3.8'
services:
    database:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: sylius
        volumes:
            - database:/var/lib/mysql

    mailer:
        image: schickling/mailcatcher
        ports:
            - 1025
            - 1080

    node:
        platform: linux/x86_64
        build:
            context: ../../infra/node/
            args:
                USER_UID: ${USER_UID}
        volumes:
            - ../../:/var/www:rw,delegated

volumes:
    database: {}
